services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db-2026
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehicle_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: ./app
    container_name: node-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: vehicle_db
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  mysql_data: